### ISSUE TITLE
Add Text instead of Numbers

### ISSUE THREAD

**Issue by Benjamin2509** [bitfocus/companion-module-malighting-grandma3#2]
By testing the new MA3 module I've seen that its not possible to reference eg. a sequence via name. It's just possible to reference it by number. Is it possible to change that? Referencing sequences, MAtricks, Groups, Quickeys, macros with a name?
Thanks for your work. The Module works great!

**Comment by blockiyt** [comment]
Hey @Benjamin2509, that's nice to hear that the plugin works great!
Sorry for the late answer, I didn't get any emails on these Issues.

It seems to work with the command 'Select Sequence "PAR"' or 'SelectFixtures Group "All PAR Grid"', so I can implement it.

**Comment by blockiyt** [comment]
Sadly, currently it's not possible to address your wish, because of #3 
The MA Support hast this as a known issue. The way I do it currently works fine, but as soon as I would use the text variant, this error would come up, and would not be fixable.

**Comment by blockiindahood** [comment]
closed because of inactivity

**Comment by blockiindahood** [comment]
Hey @Benjamin2509,

since one of the new updates of grandMA, we have now the possibility to reference Quickeys, Groups, Sequences, MATricks, Plugins and Macros via their names.

I just published a new version, that should get published to companion during the next build cycle of them.

**Comment by Benjamin2509** [comment]
Thanks for Adding that.
