### ISSUE TITLE
Quick keys stick to mousebutton

### ISSUE THREAD

**Issue by tobiashalling** [bitfocus/companion-module-malighting-grandma3#3]
First of all, GREAT plugin, love it. All tho:

After configuring some quickkeys, it seems like "delete" or "copy" sticks to my mousebutton.

Also, anything concerning "clear" both quickkey and cmd gives me the following error:
"Clould not open file C:/ProgramData/MALightingTechnology/gma3_1.9.7/onpc/temp/undo/Undo_0_0 for writing"
![Clear temp issue](https://github.com/bitfocus/companion-module-malighting-grandma3/assets/81563428/ecdd4785-d24b-4d86-a94c-47184eff222e)

Idk if this is a problem isolated to my pc or if it is a general problem. 

Look forward to hearing from you

**Comment by blockiyt** [comment]
Hey @tobiashalling, nice to hear that you love the plugin!
Sorry for the late answer, I didn't receive any emails on this one.

I should've fixed the problem in version [1.0.2](https://github.com/bitfocus/companion-module-malighting-grandma3/releases/tag/v1.0.2). Which Version are you running?

**Comment by blockiindahood** [comment]
closed because of inactivity
