### ISSUE TITLE
GrandMA3 Feedback

### ISSUE THREAD

**Issue by ethanmatthews** [bitfocus/companion-module-malighting-grandma3#5]
Just getting into using this module in my companion instance and I was curious if there were ever plans to add feedback from MA or if that is even possible with OSC.

**Comment by blockiyt** [comment]
Hey @ethanmatthews ✌🏼

MA does not natively support feedback for OSC. You'd have to write a plugin that sends every X seconds feedback via the OSC interface of the MA, that then could be received by this companion module. If u have LUA experience, you could do it yourself. It is possible that I will provide such an plugin, but not im nest future.

**Comment by einlichtvogel** [comment]
You are absolutely right!

These are the ones that give feedback natively:
![image](https://github.com/user-attachments/assets/32186cb3-a814-4465-9d59-ed3ea31bf47b)

If you are interested you are welcome to make an PR, I can hand you the OSC docs over. 

If not I'll can do this July / August, or if I am free on any weekend in near future.

**Comment by kinglevel** [comment]
> tbh, at this time I don't think that the stuff thats needs to be done is in any relation to the effort thats needed to develop this. since the only thing you can change is the style of a button...
> 
> companions feedback engine would have to be a lot more opener.
> 
> could you name me an exact example for your use case?

But it is so much more than that!

You could for example move a fader or jog on the left jog wheels and scrub in reaper! Very powerful! Feedback must be implemented somehow one day.

**Comment by einlichtvogel** [comment]
> I now made an release with the first function: check if an sequence is running as feedback.
> 
> Submitted it and currently waiting for the okay from Bitfocus.

currently there seems to be more problems than expected, the release is taking longer than expected.
have to tell MA Support about it.

**Comment by angelback** [comment]
Hey!

Have there been any updates on this topic in the last month and a half?

I'm super interested in this feedback function for gMA3!

**Comment by einlichtvogel** [comment]
Hey @angelback,

nothing new here. Currently sporadically testing with @RyanSceneTeknikk but because of my lack of time I currently can't develop it through. In july it will be better.

**Comment by omnivoxaps** [comment]
Wouw, really exiting if we could get the current cue number from a theatre cuelist sequence into companion!

It would mean a lot to many theatres that uses ma3.
