### ISSUE TITLE
MA3 Cræshing when pressing oops and Please not working.

### ISSUE THREAD

**Issue by Knutvals** [bitfocus/companion-module-malighting-grandma3#6]
So I have Companion 3.3.1 running talking to my Macbook running MA3onPC 2.0.2

When i press oops multible times MA completly crashes. 

I have the buttons mapped to Quickeys and all the other buttons seem to work fine except for Oops that crashes onPC, and Please that works for a lot of comandos, but not when i try to use the comando "Store cue 1" to the selected cue, if a cue already exsist and the popup dialog would normally pop up i get the error: "User Canceled Command" if this is a new cue it works as intended.

**Comment by Knutvals** [comment]
After some further testing i have found a workaroud.

Choosing the "Run Command" action in companion and typing "Go Quickey 100" The please functionality works as intended.

**Comment by blockiyt** [comment]
Hey @Knutvals!

The issue that ma crashes is not an error of the plugin, it is an error of how the onPC software is handling the commands I'm sending to it.

I already reported it to MA, they said they know about this issue but don't know when it's being fixed.

The problem with "Go+ Quickey X" is, that some quickeys need a push and release signal, and "Go+" is just pushing it, not releasing it. I don't know if that behavior changed, I'll have to try it out.

**Comment by blockiyt** [comment]
Interestingly, my setup with please works like a charm.
Sometimes it crashes when I use the esc key, but no problems at all besides of that.

**Comment by blockiindahood** [comment]
closed because of inactivity
